# Generated by Django 5.1.4 on 2024-12-12 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='usuario_que_valora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_hechas', to=settings.AUTH_USER_MODEL),
        ),
    ]
